version: "3.9"
services:
  mongo:
    image: mongo:4.2.5
    #ports:
    #  - "27018:27017"

  redis:
    image: redis:latest
    container_name: redis_container  # Optional: Name the Redis container
    #ports:
    #  - "6379:6379"  # Map the default Redis port
    volumes:
      - redis_data:/data  # Persist Redis data
    restart: unless-stopped  # Ensure Redis restarts automatically

  app:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017,redis:6379  # Wait for MongoDB and Redis to be ready
    ports:
      - "8080:8080"

volumes:
  redis_data:  # Volume for Redis data persistence
